ProjectTestDelivery/Controllers/CourierController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjectTestDelivery.Models;
namespace ProjectTestDelivery.Controllers
{
    public class CourierController : Controller
    {

        readonly ApplicationDbContext dbContext = new ApplicationDbContext();

        // GET: CourierController
        public ActionResult Index()
        {
            List<Courier> courierList = dbContext.GetAllCouriers().ToList();
            return View(courierList);
        }

        // GET: CourierController/Details/5
        public ActionResult Details(int id)
        {
            if (id <= 0) return NotFound();
            Courier courier = dbContext.GetCourier(id);
            courier.ItemList = new List<Item>();
            courier.ItemList = dbContext.GetAllItems().Where(i => i.CourierId == id || i.CourierId == null || i.CourierId == 0 ).ToList();
            if (courier == null)
            {
                return NotFound();
            }
            return View(courier);
        }

        // GET: CourierController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CourierController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Courier courier)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    dbContext.CreateCourier(courier);
                    return Redirect("Index");
                }

                return View(courier);
            }
            catch
            {
                ViewBag.ErrorMsg = "Something went wrong.";
                return View();
            }
        }

        // GET: CourierController/Edit/5
        public ActionResult Edit(int id, int? courierId)
        {
            if (id <= 0) return NotFound();
            Courier courier = dbContext.GetCourier(id);
            if (courier == null)
            {
                return NotFound();
            }
            return View(courier);
        }

        // POST: CourierController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Courier courier)
        {
            if (id <= 0) return NotFound();
            try
            {
                if (ModelState.IsValid)
                {
                    dbContext.UpdateCourier(courier);
                    return RedirectToAction(nameof(Index));
                }

                return View(dbContext);
            }
            catch
            {
                ViewBag.ErrorMsg = "Something went wrong.";
                return View();
            }
        }

        // GET: CourierController/Delete/5
        public ActionResult Delete(int id)
        {
            if (id <= 0) return NotFound();
            Courier courier = dbContext.GetCourier(id);
            if (courier == null)
            {
                return NotFound();
            }
            return View(courier);
        }

        // POST: CourierController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Courier courier)
        {
            try
            {
                dbContext.DeleteCourier(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewBag.ErrorMsg = "Something went wrong.";
                return View();
            }
        }

        public ActionResult AssignToCourier(int courierId=0, int itemId=0)
        {

            try
            {
                dbContext.AssignToCourier(itemId, courierId);
                return RedirectToAction("Details", new {id= courierId });
            }
            catch
            {
                ViewBag.ErrorMessage = "Something went wrong.";
                return View(ViewBag.ErrorMessage);
            }
        }

    }
}

ProjectTestDelivery/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjectTestDelivery.Models;

namespace ProjectTestDelivery.Controllers
{
    public class CustomerController : Controller
    {
        readonly ApplicationDbContext dbContext = new ApplicationDbContext();
         
        // GET: CustomerController
        public ActionResult Index()
        {
            List<Customer> customerList = dbContext.GetAllCustomers().ToList();
            return View(customerList);
        }

        // GET: CustomerController/Details/5
        public ActionResult Details(int id)
        {
            if (id <= 0) return NotFound();
            Customer customer = dbContext.GetCustomer(id);
            customer.ItemList = new List<Item>();
            customer.ItemList = dbContext.GetAllItems().Where(i => i.CustomerId == id).ToList();
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // GET: CustomerController/Create
        public ActionResult Create()
        {
            return View();
            
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Customer customer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    dbContext.CreateCustomer(customer);
                    return Redirect("Index");
                }

                return View(customer);
            }
            catch
            {
                ViewBag.ErrorMsg = "Something went wrong.";
                return View();
            }
        }

        // GET: CustomerController/Edit/5
        public ActionResult Edit(int id)
        {
            if (id <= 0) return NotFound();
            Customer customer = dbContext.GetCustomer(id);
            if (customer == null) 
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: CustomerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Customer customer)
        {
            if (id <= 0) return NotFound();
            try
            {
                if (ModelState.IsValid)
                {
                    dbContext.UpdateCustomer(customer);
                    return RedirectToAction(nameof(Index));
                }

                return View(customer);
            }
            catch
            {
                ViewBag.ErrorMsg = "Something went wrong.";
                return View(customer);
            }
        }

        // GET: CustomerController/Delete/5
        public ActionResult Delete(int id)
        {
            if (id <= 0) return NotFound();
            Customer customer = dbContext.GetCustomer(id);
            if (customer == null) 
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: CustomerController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                dbContext.DeleteCustomer(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewBag.ErrorMsg = "Something went wrong.";
                return View();
            }
        }
    }
}

ProjectTestDelivery/Controllers/ItemController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using ProjectTestDelivery.Models;
using System.Diagnostics.Metrics;
using System.Threading.Tasks;

namespace ProjectTestDelivery.Controllers
{
    public class ItemController : Controller
    {
        readonly ApplicationDbContext dbContext = new ApplicationDbContext();
        private readonly IWebHostEnvironment _hostEnvironment;

        public ItemController(IWebHostEnvironment hostEnvironment)
        {
            this._hostEnvironment = hostEnvironment;
        }

        // GET: ItemController
        public ActionResult Index(ItemVM? itemVM)
        {
            if (itemVM == null)
            {
                itemVM = new ItemVM();
            }

            string wwwRootPath = _hostEnvironment.WebRootPath;
            string path = wwwRootPath + "/Files/";
            string httpPath = HttpContext.Request.Scheme + "://" + HttpContext.Request.Host + "/Files/";
            List<Item> itemList = dbContext.GetAllItems().ToList();
            if (!string.IsNullOrEmpty(itemVM.searchCustomerName))
            {
                itemList = itemList.Where(s => s.Customer.LastName.ToLower().Replace(" ","").Contains(itemVM.searchCustomerName.ToLower().Replace(" ", ""))
                                       || s.Customer.FirstName.ToLower().Replace(" ", "").Contains(itemVM.searchCustomerName.ToLower().Replace(" ", ""))).ToList();
            }

            if (!string.IsNullOrEmpty(itemVM.searchCourierName))
            {
                itemList = itemList.Where(s => s.Courier.LastName.ToLower().Replace(" ", "").Contains(itemVM.searchCourierName.ToLower().Replace(" ", ""))
                                       || s.Courier.FirstName.ToLower().Replace(" ", "").Contains(itemVM.searchCourierName.ToLower().Replace(" ", ""))).ToList();
            }

            if (itemVM.status != null)
            {
                itemList = itemList.Where(s => s.StatusType == itemVM.status).ToList();
            }

            if (itemVM.searchByDate != null) {
                itemList = itemList.Where(s => s.CreatedDate.Date == itemVM.searchByDate).ToList();
            }
            itemVM.itemList = itemList;

            return View(itemVM);
        }

        // GET: ItemController/Details/5
        public ActionResult Details(int id)
        {
            if (id <= 0) return NotFound();
            Item item = dbContext.GetItem(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // GET: ItemController/Create
        public ActionResult Create(int? customerId, int? CourierId)
        {
            var item = new Item();
            item.CourierId = CourierId;
            item.CustomerId = customerId;
            item.AssignedCourier = new List<SelectListItem>();
            item.Owner = new List<SelectListItem>();
            List<Courier> courierList = dbContext.GetAllCouriers().ToList();
            
            foreach (var courier in courierList)
            {
                item.AssignedCourier.Add(new SelectListItem { 
                    Text = courier.FirstName + ' ' + courier.LastName,
                    Value = courier.CourierId.ToString()
                });
            }

            List<Customer> customerList = dbContext.GetAllCustomers().ToList();

            foreach (var customer in customerList)
            {
                item.Owner.Add(new SelectListItem
                {
                    Text = customer.FirstName + ' ' + customer.LastName,
                    Value = customer.CustomerId.ToString()
                });
            }

            return View(item);
        }

        // POST: ItemController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Item item)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (item.ProofFile != null)
                    {
                        string wwwRootPath = _hostEnvironment.WebRootPath;
                        string fileName = Path.GetFileNameWithoutExtension(item.ProofFile.FileName);
                        string extension = Path.GetExtension(item.ProofFile.FileName);
                        item.ProofName = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        string path = Path.Combine(wwwRootPath + "/Files/", fileName);
                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await item.ProofFile.CopyToAsync(fileStream);
                        }
                    }

                    dbContext.CreateItem(item);

                    return Redirect("Index");
                }

                return View(item);
            }
            catch
            {
                ViewBag.ErrorMsg = "Something went wrong.";
                return View();
            }
        }

        // GET: ItemController/Edit/5
        public ActionResult Edit(int id, int? courierId)
        {
            if (id <= 0) return NotFound();
            Item item = dbContext.GetItem(id);
            item.AssignedCourier = new List<SelectListItem>();
            item.Owner = new List<SelectListItem>();
            List<Courier> courierList = dbContext.GetAllCouriers().ToList();
            
            foreach (var courier in courierList)
            {
                item.AssignedCourier.Add(new SelectListItem
                {
                    Text = courier.FirstName + ' ' + courier.LastName,
                    Value = courier.CourierId.ToString()
                });
            }

            List<Customer> customerList = dbContext.GetAllCustomers().ToList();
            
            foreach (var customer in customerList)
            {
                item.Owner.Add(new SelectListItem
                {
                    Text = customer.FirstName + ' ' + customer.LastName,
                    Value = customer.CustomerId.ToString()
                });
            }
            if (item == null)
            {
                return NotFound();
            }
            item.StatusType = courierId != null ? 1 : item.StatusType;
            ViewBag.MarkAsDelivered = courierId != null ? true : false;
            return View(item);
        }

        // POST: ItemController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Item item)
        {
            if(id <= 0) return NotFound();
            item.AssignedCourier = new List<SelectListItem>();
            item.Owner = new List<SelectListItem>();
            List<Courier> courierList = dbContext.GetAllCouriers().ToList();

            foreach (var courier in courierList)
            {
                item.AssignedCourier.Add(new SelectListItem
                {
                    Text = courier.FirstName + ' ' + courier.LastName,
                    Value = courier.CourierId.ToString()
                });
            }

            List<Customer> customerList = dbContext.GetAllCustomers().ToList();

            foreach (var customer in customerList)
            {
                item.Owner.Add(new SelectListItem
                {
                    Text = customer.FirstName + ' ' + customer.LastName,
                    Value = customer.CustomerId.ToString()
                });
            }
            try
            {
                if (ModelState.IsValid)
                {
                    if (item.ProofFile != null)
                    {
                        string wwwRootPath = _hostEnvironment.WebRootPath;
                        string fileName = Path.GetFileNameWithoutExtension(item.ProofFile.FileName);
                        string extension = Path.GetExtension(item.ProofFile.FileName);
                        item.ProofName = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        string path = Path.Combine(wwwRootPath + "/Files/", fileName);
                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await item.ProofFile.CopyToAsync(fileStream);
                        }
                    }

                    dbContext.UpdateItem(item);
                    return RedirectToAction(nameof(Index));
                }

                return View(item);
            }
            catch
            {
                ViewBag.ErrorMsg = "Something went wrong.";
                return View(item);
            }
        }

        // GET: ItemController/Delete/5
        public ActionResult Delete(int id)
        {
            if (id <= 0) return NotFound();
            Item item = dbContext.GetItem(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // POST: ItemController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Item item)
        {
            if (id <= 0) return NotFound();
            try
            {
                dbContext.DeleteItem(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewBag.ErrorMsg = "Something went wrong.";
                return View(item);
            }
        }

        public ActionResult DownloadFile(string fileName)
        {
            string wwwRootPath = _hostEnvironment.WebRootPath;
            if (string.IsNullOrEmpty(fileName)) return NotFound();
            string path = Path.Combine(wwwRootPath + "/Files/", fileName);
            byte[] bytes = System.IO.File.ReadAllBytes(path);

ProjectTestDelivery/Views/Courier/Create.cshtml
@model ProjectTestDelivery.Models.Courier

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Courier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectTestDelivery/Views/Courier/Delete.cshtml
@model ProjectTestDelivery.Models.Courier

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Courier</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CourierId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CourierId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProjectTestDelivery/Views/Courier/Details.cshtml
@model ProjectTestDelivery.Models.Courier

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Courier</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CourierId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CourierId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id= Model.CourierId}) |
    <a asp-action="Index">Back to List</a>
</div>
<div class="margin-top-lg">
    <h4>Courier's Assigned Items</h4>
</div>
<table class="table">

    <thead>
        <tr>
            <th>
                Item Name
            </th>
            <th>
                Item Description
            </th>
            <th>
                Customer Name
            </th>
            <th>
                Customer Address
            </th>
            <th>
                Delivery Status
            </th>
            <th>
                Date Created
            </th>
            <th>
                Proof
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ItemList.Where(i=>i.CourierId == Model.CourierId))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemDescription)
                </td>
                <td>
                    @Html.ActionLink(item.Customer.FirstName + " " + item.Customer.LastName, "Details", "Courier",new{id=item.CourierId })
                </td>
                <td>
                    @(item.Customer.Address)
                </td>
                <td>
                    @(item.StatusType == 1 ? "Delivered" : item.StatusType == 2 ? "Cancelled" : "On Hold")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    @Html.ActionLink(item.ProofName, "DownloadFile", new{fileName = item.ProofName})
                </td>
                <td>
                    @if(item.StatusType == 0 ){
                        @Html.ActionLink("Mark as Delivered", "Edit", "Item", new { id=item.ItemId, courierId = Model.CourierId })
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
@if (Model.ItemList.Where(i => i.CourierId == 0).Count() > 0)
{
    <div class="margin-top-lg">
        <h4>Unassigned Items</h4>
    </div>
    <table class="table">

        <thead>
            <tr>
                <th>
                    Item Name
                </th>
                <th>
                    Item Description
                </th>
                <th>
                    Customer Name
                </th>
                <th>
                    Customer Address
                </th>
                <th>
                    Delivery Status
                </th>
                <th>
                    Date Created
                </th>
                <th>
                    Proof
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ItemList.Where(i => i.CourierId == 0))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ItemName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ItemDescription)
                    </td>
                    <td>
                        @Html.ActionLink(item.Customer.FirstName + " " + item.Customer.LastName, "Details", "Customer",new{id=item.CustomerId })
                    </td>
                    <td>
                        @(item.Customer.Address)
                    </td>
                    <td>
                        @(item.StatusType == 1 ? "Delivered" : item.StatusType == 2 ? "Cancelled" : "On Hold")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedDate)
                    </td>
                    <td>
                        @Html.ActionLink(item.ProofName, "DownloadFile", new{fileName = item.ProofName})
                    </td>
                    <td>
                        @Html.ActionLink("Take Parcel", "AssignToCourier", new { courierId = Model.CourierId, itemId = item.ItemId })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

ProjectTestDelivery/Views/Courier/Edit.cshtml
@model ProjectTestDelivery.Models.Courier

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Courier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden readonly>
                <label asp-for="CourierId" class="control-label"></label>
                <input asp-for="CourierId" class="form-control" />
                <span asp-validation-for="CourierId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group" hidden readonly>
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectTestDelivery/Views/Courier/Index.cshtml
@model IEnumerable<ProjectTestDelivery.Models.Courier>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CourierId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourierId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.CourierId }, new{@class = "float-right btn btn-success btn-options"}) |
                @Html.ActionLink("Details", "Details", new { id=item.CourierId  }, new{@class = "float-right btn btn-warning btn-options"}) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.CourierId  }, new{@class = "float-right btn btn-danger btn-options"} )
            </td>
        </tr>
}
    </tbody>
</table>